### ISSUE TITLE
FYI - This is why this crate is necessary

### ISSUE THREAD

**Issue by AzureMarker** [Meziu/rust-linker-fix-3ds#2]
`postix_memalign` is not available by default so Rust3DS forked the system allocator:
https://github.com/rust3ds/alloc_system3ds/issues/6

I was curious why we don't have to register our own allocator, and the reason is that this crate adds `postix_memalign` for the upstream system allocator to use.

**Comment by Meziu** [comment]
I prefer having as little crates as possible, and since i needed this crate for realpath anyways, posix_memalign was added too. I had to fix many errors before getting to where I am now...

**Comment by AzureMarker** [comment]
Yeah I agree using the built in allocator is best. But maybe we can avoid even this crate if libc could contain these functions? What do you think? I'm not sure if that fits within the libc crate's scope.

**Comment by Meziu** [comment]
Nope, let's avoid changing libc more than absolutely needed. Still, this crate doesn't need to be recompiled any time soon, so i don't see a problem just keeping it here and having a pre-compiled lib in ctru-rs.
