### ISSUE TITLE
Support `CLOCK_MONOTONIC` in `clock_gettime`

### ISSUE THREAD

**Issue by ian-h-chamberlain** [Meziu/rust-linker-fix-3ds#9]
From discussion starting at https://github.com/Meziu/rust-horizon/issues/6#issuecomment-1026109044

---- 

Looking at [the implementation of `osGetTime`](https://github.com/devkitPro/libctru/blob/4d36c74be427d34ff8c7b06146893dccef43dcd5/libctru/source/os.c#L67) (which is used by `gettimeofday`, which in turn is used by our `clock_gettime` impl for `CLOCK_REALTIME`), they appear to do some adjustment for clock drift in an _attempt_ to get monotonic values, but I'm not sure if that implies the value from `svcGetSystemTick()` is not normally monotonic? There is also an epoch adjustment from 1900 to 1970 [here](https://github.com/devkitPro/libctru/blob/4d36c74be427d34ff8c7b06146893dccef43dcd5/libctru/source/system/syscalls.c#L32) for `gettimeofday`, but I don't think that would be strictly needed for a monotonic `clock_gettime`...

So maybe we could try our own impl that basically looks like this?
```rust
let now = svcGetSystemTick();
// Not sure if the math is quite right but you get the idea...
(*tp).tv_sec = now / SYSCLOCK_ARM11;
(*tp).tv_nsec = 1000 * (now - SYSCLOCK_ARM11*(*tp).tv_sec) / CPU_TICKS_PER_USEC;
```
I have to imagine that `svcGetSystemTick()` is monotonic, since I think it's supposed to be the number of clock cycles since boot, based on [this docstring](https://github.com/devkitPro/libctru/blob/4d36c74be427d34ff8c7b06146893dccef43dcd5/libctru/include/3ds/os.h#L17)

_Originally posted by @ian-h-chamberlain in https://github.com/Meziu/rust-horizon/issues/6#issuecomment-1026196436_

---- 

I can work on this soon but wanted to track it here, also wanted to wait for the discussion in https://github.com/Meziu/rust-linker-fix-3ds/pull/8 to be finalized so we can come up with a best practice for exposing `libctru` APIs through libc like this, since the error handling will probably be similar.

**Comment by AzureMarker** [comment]
I just ran into this when trying to write a Tokio example. It needs monotonic time for its "time" feature.
